- name: install httpd
  yum: name={{packages}} state=present
  vars:
    packages:
      - httpd
      - httpd-tools

- name: 分发registry介质
  copy: src={{ base_dir }}/packages/bin/registry dest={{ bin_dir }}/ mode=0755

- name: 配置registry conf文件
  template: src=config.yml.j2 dest={{ conf_dir }}/config.yml mode=0755

- name: 创建/etc/pki/registry目录
  file: path={{item}} state=directory mode=0755
  with_items:
    - '/etc/pki/registry'
    - '/etc/docker/certs.d/{{DOCKER_REG_DOMAIN}}:{{REG_PORT}}'

- include: "create-ca.yml"

- name: create pki
  shell: cp -r /tmp/cert/ /etc/pki/registry/

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ DOCKER_REG_DOMAIN }}$'
    line: '{{item}} {{ DOCKER_REG_DOMAIN }}'
    state: present
  with_items: '{{ groups["registry"] }}'

- name: cp cert_file to /etc/docker/certs.d
  shell: cp /etc/pki/registry/{{DOCKER_REG_DOMAIN}}.crt /etc/docker/certs.d/{{DOCKER_REG_DOMAIN}}:{{REG_PORT}}/ca.crt

- include: "start_rg.yml"
