- name: copy registry.service
  template: src="registry.service.j2" dest=/usr/lib/systemd/system/registry.service

- name: daemon-reload
  shell: systemctl daemon-reload

- name: boot registry
  service: name=registry.service state=restarted enabled=yes

- name: test docker connect
  shell: docker login -udocker -pdocker {{ DOCKER_REG_DOMAIN }}:{{ REG_PORT }}
  ignore_errors: false
