# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker

stages:
    - builds
    - deploy

prepare:
    stage: builds
    script:
      - sudo ln -s $CI_PROJECT_DIR /etc/ansible

run:
    stage: deploy
    script:
      - sudo ln -s /home/gitlab-runner/deployer/packages /etc/ansible/packages
      - sudo ln -s /home/gitlab-runner/deployer/hosts /etc/ansible/hosts
      - sudo ansible-playbook 01.prepare.yml
