- name: 分发sriov-controller二进制文件
  copy: src={{ base_dir }}/packages/dbscale/{{ item }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
    - "{{ NETWORK_CONTROLLER }}"
  tags: upgrade_k8s

- name: 创建sriov-controller的systemd unit文件
  template: src=network-controller.service.j2 dest=/etc/systemd/system/{{ NETWORK_CONTROLLER }}.service

- name: 开机启用sriov-controller服务
  shell: systemctl enable "{{ NETWORK_CONTROLLER }}"
  ignore_errors: true

- name: 开启sriov-controller服务
  shell: systemctl daemon-reload && systemctl restart "{{ NETWORK_CONTROLLER }}"
  tags: upgrade_k8s
