- name: 分发sriov-plugin二进制文件
  copy: src={{ base_dir }}/packages/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
    - "{{ NETWORK_PLUGIN }}"
  tags: upgrade_k8s

- name: 准备sriov-plugin脚本目录
  file: path={{ scripts_dir }} state=directory mode=0755

- name: 分发sriovMGR脚本文件
  unarchive: src={{ base_dir }}/packages/scripts/sriovMGR.tar dest={{ scripts_dir }} mode=0755
  tags: upgrade_k8s

- name: 清空默认conf配置
  shell: mv /etc/cni/net.d/* /tmp

- name: 部署sriov-plugin配置文件
  template: src=network-plugin.conf.j2 dest=/etc/cni/net.d/{{ NETWORK_PLUGIN }}.conf
